---
#####################
#
# Steps configuration
#
#####################

# !!! WARNING !!!
#
# Before modifiyng PLEASE read the documenation
# and make sure that you completly understand what
# means each step and how it impacts other steps
#
# !!! WARNING !!!

# Perform force apt-get update
apt_update: false

# Clean gathered customizations on nodes and Fuel
#
# Be carefull, you can loose your INITIAL customizations
# if you perform it after failed upgrade or applying some patches!!!
clean_customizations: false

