---
#####################
#
# Steps configuration
#
#####################

# !!! WARNING !!!
#
# Before modifiyng PLEASE read the documenation
# and make sure that you completly understand what
# means each step and how it impacts other steps
#
# !!! WARNING !!!

# Perform apt-get update
apt_update: true

# Clean gathered customizations on nodes and Fuel
#
# Be carefull, you can loose your INITIAL customizations
# if you perform it after failed upgrade or applying some patches!!!
clean_customizations: false

# All your customizations will be copied to patches folder on nodes
# and then veified and applied
use_current_customizations: true

# Which packet should be used for verification
# - Installed
# - Candidate
#
# If you want istall MU you shoud use 'Candidate'
# If you want just appy new patch on the current installation
# you need to use 'Installed' and enable 'use_current_customizations"
pkg_ver_for_verifiacation: "Candidate"

# Rollback on the specified release
rollback: false

# Apply all patches from patches folder
apply_patches: true
