---
#####################
#
# Steps configuration
#
#####################

# !!! WARNING !!!
#
# Before modifiyng PLEASE read the documenation
# and make sure that you completly understand what
# means each step and how it impacts other steps
#
# !!! WARNING !!!

# Perform apt-get update
apt_update: true

# Which packet should be used for verification
# - Installed
# - Candidate
#
# If you want istall MU you shoud use 'Candidate'
# If you want just appy new patch on the current installation
# you need to use 'Installed' and enable 'use_current_customizations"
pkg_ver_for_verifiacation: "Candidate"

# Ignore already applied patches
# Disable by default since it might be double checked for avoiding any issues
ignore_applied_patches: "False"
