---

- name: Clean APT files on host
  file:
    path: "{{ apt_dir }}"
    state: absent

- name: Create APT config directory
  file:
    path: "{{ apt_dir }}/sources.list.d"
    state: directory
  when: env_release == mos_release

- name: Generate sources.lists for configured repos
  template:
    src: "sources.list.j2"
    dest: "{{ apt_dir }}/sources.list.d/{{ item.name }}.list"
    force: yes
  with_items: "{{ apt_repos }}"

- name: Copy configured sources.lists
  copy:
    remote_src: True
    src: "{{ item.path }}"
    dest: "{{ apt_dir }}/sources.list.d/{{ item.name }}.list"
  with_items: "{{ apt_sources_lists }}"

- name: Copy apt.conf
  template:
    src: "apt.conf.j2"
    dest: "{{ apt_conf }}"
    force: yes

- name: APT Update
  command: apt-get -c {{ apt_conf }} update

