---

- name: APT correct dependencies
  command: "apt-get -y -c {{ apt_conf }} -f install"
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: APT upgrade
  command: "apt-get -y -c {{ apt_conf }} upgrade"
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: APT reinstall customized packages
  command: "apt-get -y -c {{ apt_conf }} install --reinstall {{ item }}"
  environment:
    DEBIAN_FRONTEND: noninteractive
  with_items: "{{ md5_verify_result.stdout_lines }}"
  when: md5_verify_result is defined
