---

- name: APT correct dependencies
  command: "apt-get -y -c {{ apt_conf }} -f install"
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: APT upgrade
  command: "apt-get -y -c {{ apt_conf }} upgrade"
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Apply customizations
  script: files/pkgs_apply_customizations.sh
  environment:
    MOS_DIR: "{{ mos_dir }}"
