---

- name: APT correct dependencies
  command: "apt-get -y -c {{ apt_conf }} -f install"
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: APT upgrade
  command: "apt-get -y -c {{ apt_conf }} upgrade"
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Apply customizations
  script: files/pkgs_apply_customizations.sh
  environment:
    CUSTOM_DIR: "{{ custom_dir }}"
    PATCHES_DIR: "{{ patches_dir }}"
    SKIP_USE_CURRENT_CUSTOMIZATIONS: "{{ skip_apply_customization }}"
  when: skip_apply_customization == True
