---

- name: Create APT config directory
  file:
    path: "{{ apt_dir }}/sources.list.d"
    state: directory
  when: env_release == mos_release

- name: Copy sources.lists
  template:
    src: "sources.list.j2"
    dest: "{{ apt_dir }}/sources.list.d/{{ item.name }}.list"
    force: yes
  with_items: repos

- name: Copy local nailgun source
  copy:
    remote_src: True
    src: "/etc/apt/sources.list.d/mos.list"
    dest: "{{ apt_dir }}/sources.list.d/nailgun.list"

- name: Copy apt.conf
  template:
    src: "apt.conf.j2"
    dest: "{{ apt_conf }}"
    force: yes

- name: APT Update
  command: apt-get update -c {{ apt_conf }}

