---

- name: Clean customization files on Fuel
  file:
    path: "{{ fuel_custom_dir }}"
    state: absent
  delegate_to: localhost
  run_once: true

- name: Clean customization files on host
  file:
    path: "{{ custom_dir }}"
    state: absent
