---

- name: Check if customizations were gathered
  stat:
    path: "{{ custom_dir }}"
  register: customizations_dir

- name: Make sure customizations directory exists
  file:
    path: "{{ custom_dir }}"
    state: directory
  when: not customizations_dir.stat.exists

- name: Make sure customizations directory for this node exists on Fuel
  file:
    path: "{{ fuel_custom_dir}}/{{ ansible_hostname }}/"
    state: directory
  delegate_to: localhost
  when: not customizations_dir.stat.exists

- name: Gather package customizations
  script: files/get_package_customizations.sh {{ item }}
  register: customizations_result
  environment:
    APT_CONF: "{{ apt_conf }}"
    CUSTOM_DIR: "{{ custom_dir }}"
  with_items: "{{ md5_verify_result.stdout_lines }}"
  when: not customizations_dir.stat.exists and
        md5_verify_result is defined and
        md5_verify_result.stdout != ""

- name: Download customizations to Fuel
  fetch:
    src:  "{{ custom_dir }}/{{ item }}/{{ item }}_customization.patch"
    dest: "{{ fuel_custom_dir }}/{{ ansible_hostname }}/"
    flat: true
  with_items: "{{ md5_verify_result.stdout_lines }}"
  when: customizations_result is defined and
        customizations_result.changed

- name: Make sure backup customizations directory exists
  run_once: true
  delegate_to: localhost
  file:
    path: "{{ fuel_custom_backup_dir }}"
    state: directory
  when: customizations_result is defined and
        customizations_result.changed

- name: Make a backup of gathered customizations
  run_once: true
  local_action: shell tar -czf "{{ fuel_custom_backup_dir }}"/customizations-$(date +%m.%d.%y_%H-%M-%S).tgz "{{ fuel_custom_dir }}"
  when: customizations_result is defined and
        customizations_result.changed

- name: Verify customizations consistency
  register: verify_customizations_result
  run_once: true
  ignore_errors: true
  local_action: script files/verify_customizations_consistency.sh
  environment:
    FUEL_CUSTOM_DIR: "{{ fuel_custom_dir }}"
    FUEL_PATCHES_DIR: "{{ fuel_patches_dir }}"
    FUEL_PROCESSED_DIR: "{{ fuel_processed_dir }}"
    FUEL_UNIFIED_DIR: "{{ fuel_unified_dir }}"
    UNIFY_ONLY_PATCHES: "{{ unify_only_patches }}"
  when: use_current_customizations is defined and
        use_current_customizations

- name: Show results of customizations consistency Verification
  run_once: true
  debug:
    msg: "{{ verify_customizations_result.stdout_lines }}"
  when: verify_customizations_result is defined

- name: Fail if verifying of customizations consistency failed
  run_once: true
  fail:
    msg: "[ERROR] Verifying of customizations consistency FAILED"
  when: verify_customizations_result is defined and
        verify_customizations_result.failed

- name: Use unified customizations
  run_once: true
  local_action: command rsync -avzrc --delete  "{{ fuel_unified_dir }}/." "{{ fuel_patches_dir }}/00-customizations"
  when: verify_customizations_result is defined and
        not verify_customizations_result.failed
