---

- name: Check customization
  script: files/pkgs_get_customizations.sh {{ item }} {{ apt_conf }}
  register: customizations_result
  environment:
    MOS_DIR: "{{ custom_dir }}"
    IGNORE_RESULT: "{{ skip_use_current_customization }}"
  with_items: "{{ verify_result.stdout_lines }}"

- name: Make sure local customizations folder exists
  local_action: file path={{ fuel_dir }}/{{ ansible_hostname }} state=directory
  when: customizations_result is defined and
        customizations_result.changed

- name: Download customizations to Fuel
  fetch:
    src:  "{{ mos_dir }}/{{ item }}/{{ item }}_customization.patch"
    dest: "{{ fuel_dir }}/{{ ansible_hostname }}/{{ item }}.patch"
    flat: true
  with_items: "{{ verify_result.stdout_lines }}"
  when: customizations_result is defined and
        customizations_result.changed

