---

- name: Make sure report directory exists
  file:
    path: "{{ report_dir }}"
    state: directory

- name: Check if customizations were already gathered
  stat:
    path: "{{ report_dir }}/md5_results"
  register: md5_results

- include: verify_md5_action.yml
  when: md5_check is defined and
        md5_check or
        not md5_results.stat.exists

- name: Read results of MD5 Sum verification
  command: cat "{{ report_dir }}/md5_results"
  register: md5_verify_result

- name: Show results of MD5 sum verification
  debug:
    msg: "{{ md5_verify_result.stdout_lines }}"
  when: md5_verify_result.stdout != ""

- name: Remove messages and leave only packages
  shell: echo "{{ md5_verify_result.stdout }}" | grep -v '^\[' | grep -v '^W\:'; exit 0
  register: md5_verify_result

