---

- name: Check MD5 sum for upgradable packages
  script: files/verify_packages_ubuntu.sh
  environment:
    APT_CONF: "{{ apt_conf }}"
  register: md5_verify_result

- name: Show results of MD5 sum verification
  debug:
    msg: "{{ md5_verify_result.stdout_lines }}"
  when: md5_verify_result is defined and
        md5_verify_result.changed

