---

- name: Clean patches folder
  file:
    path: "{{ patches_dir }}"
    state: absent

- name: Clean verification folder
  file:
    path: "{{ verification_dir }}"
    state: absent

- name: Sync configured patches
  synchronize:
    src: "{{ fuel_patches_dir}}/."
    dest: "{{ patches_dir}}"
    delete: true
    recursive: true
  when: rollback is undefined or
        not rollback

- name: Use current customizations
  script: files/use_customizations.sh
  environment:
    CUSTOM_DIR: "{{ custom_dir }}"
    PATCHES_DIR: "{{ patches_dir }}/00-customizations"
  when: use_current_customizations is defined and
        use_current_customizations

- name: Verify patches
  script: files/verify_patches.sh
  environment:
    APT_CONF: "{{ apt_conf }}"
    PATCHES_DIR: "{{ patches_dir }}"
    VERIFICATION_DIR: "{{ verification_dir }}"
    PKG_VER_FOR_VERIFICATION: "{{ pkg_ver_for_verifiacation }}"
  register: verify_patches_result

- name: Show results of Patches Verification
  debug:
    msg: "{{ verify_patches_result.stdout_lines }}"
  when: verify_patches_result is defined and
        verify_patches_result.changed
