---

- hosts: env_{{ env_id }}
  any_errors_fatal: true
  vars:
      steps: "apply_mu"

  vars_files:
    - "vars/mos_releases/{{ mos_release }}.yml"
    - "vars/steps/{{ steps }}.yml"

  tasks:
    - include: tasks/apt_update.yml

    - include: tasks/gather_customizations.yml

    - include: tasks/verify_customizations.yml

    - include: tasks/verify_patches.yml

    - include: tasks/apt_upgrade.yml

    - include: tasks/apply_patches.yml

- include: restart_services.yml

