---

- hosts: all:!fuel
  any_errors_fatal: true
  vars:
      steps: "apply_mu"

  vars_files:
    - "vars/mos_releases/{{ mos_release }}.yml"
    - "vars/steps/{{ steps }}.yml"

  tasks:
    - include: tasks/apt_update.yml
      when: apt_update is defined and
            apt_update

    - include: tasks/get_current_mu.yml
      when: rollback is undefined or
            not rollback

    - include: tasks/verify_md5.yml

    - include: tasks/clean_customizations.yml
      when: clean_customizations is defined and
            clean_customizations

    - include: tasks/gather_customizations.yml

    - include: tasks/verify_patches.yml

    - include: tasks/apt_upgrade.yml
      when: apt_upgrade is defined and
            apt_upgrade

    - include: tasks/apply_patches.yml
      when: apply_patches is defined and
            apply_patches

- include: restart_services.yml

