---

- hosts: all:!fuel
  gather_facts: false

  vars_files:
    - "vars/7.0.yml"

  tasks:
    - name: Clean customizations files on Fuel
      file:
        path: "{{ fuel_custom_dir }}"
        state: absent
      delegate_to: localhost
      run_once: true
      when: not skip_clean

    - name: Clean all files on host
      file:
        path: "{{ mos_dir }}"
        state: absent
      when: not skip_clean
