---

- hosts: all:!fuel

  vars_files:
    - "vars/mos_releases/{{ mos_release }}.yml"
    - "vars/steps/gather_customizations.yml"

  tasks:
    - include: tasks/health_checks.yml
      when: skip_health_check is undefined or
            not skip_health_check

    - include: tasks/apt_update.yml
      when: apt_update is defined and
            apt_update

    - include: tasks/get_current_mu.yml

    - include: tasks/verify_md5.yml

    - include: tasks/clean_customizations.yml
      when: clean_customizations is defined and
            clean_customizations

    - include: tasks/gather_customizations.yml

