---

- hosts: env_{{ env_id }}
  any_errors_fatal: true

  vars_files:
    - "vars/mos_releases/{{ mos_release }}.yml"
    - "vars/steps/gather_customizations.yml"

  tasks:
    - include: tasks/health_checks.yml
      when: health_check is defined and
            health_check

    - include: tasks/apt_update.yml

    - include: tasks/gather_customizations.yml
