---

- hosts: fuel
  connection: local
  any_errors_fatal: true
  vars_files:
    - "vars/common.yml"
    - "vars/mos_releases/{{ mos_release }}.yml"

  tasks:
  - name: Add MOS 9.2 repo
    script: files/add_repo_to_env.sh
    environment:
      ENV_ID: "{{ env_id }}"
      NAME: "mos9.2"
      TYPE: "deb"
      URL: "{{ fuel_url }}/snapshots/{{ snapshot_repo }}"
      SUITE: "mos9.0-proposed"
      SECTION: "main restricted"
      PRIORITY: "1050"


- hosts: env_{{ env_id }}
  any_errors_fatal: true
  vars_files:
    - "vars/common.yml"
    - "vars/mos_releases/{{ mos_release }}.yml"

  tasks:
  - name: Fix apt-preferences
    command: sed -i -e 's|n=mos9.0-updates|n=mos9.0|' /etc/apt/preferences.d/mos-updates.pref
    ignore_errors: true

  - name: Add MOS 9.2 repo key
    apt_key:
        url={{ fuel_url }}/snapshots/{{ snapshot_repo }}/archive-mos9.0-proposed.key

  - name: Update MCollective
    apt:
      update_cache: yes
      name: "{{ item }}"
      state: latest
    with_items:
      - nailgun-agent
      - nailgun-mcagents

  - name: Restart MCollective
    service:
      name: mcollective
      state: restarted

