---

- hosts: env_{{ env_id }}
  any_errors_fatal: true
  vars:
      steps: "apply_mu"

  vars_files:
    - "vars/common.yml"
    - "vars/mos_releases/{{ mos_release }}.yml"
    - "vars/steps/{{ steps }}.yml"

  tasks:

    - include: tasks/apply_patches.yml

- include: restart_services.yml
