---

- hosts: fuel
  connection: local
  vars:
    - mos9_centos_repo: http://mirror.fuel-infra.org/mos-repos/centos/mos9.0-centos7/updates/x86_64/
    - mos9_GPG_KEY: http://mirror.fuel-infra.org/mos-repos/centos/mos9.0-centos7/updates/RPM-GPG-KEY-mos9.0

  vars_files:
    - "vars/common.yml"

  tasks:
    - name: Add new MOS9 repository
      command: yum-config-manager --add-repo="{{ mos9_centos_repo }}"
      register: result_add_repo
      failed_when: result_add_repo | failed and
                   "as is a duplicate of an existing repo" not in result_add_repo.msg

    - name: Download GPG KEY
      command: rpm --import "{{ mos9_GPG_KEY }}"

    - name: Clean YUM Cache
      command: yum clean all

    - name: Install Cudet package
      command: yum install -y python-cudet

    - name: Prepare Master
      command: update-prepare prepare master

    - name: Prepare Environment
      command: update-prepare prepare env "{{ env_id }}"

