---

- hosts: env_{{ env_id }}
  any_errors_fatal: true

  vars_files:
    - "vars/mos_releases/{{ mos_release }}.yml"
    - "vars/steps/rollback.yml"

  tasks:
    - include: tasks/health_checks.yml
      when: health_check is defined and
            health_check

    - include: tasks/apt_update.yml

    - name: Save current locked packages
      shell:  apt-mark showhold
      register: locked_packages

    - block:
      - include: tasks/gather_customizations.yml

      - include: tasks/verify_customizations.yml

      - include: tasks/verify_patches.yml

      - include: tasks/rollback_upgrade.yml

      - include: tasks/apply_patches.yml

      always:
        - name: Restore locked packages
          shell: apt-mark showhold | xargs apt-mark unhold; echo "{{ locked_packages.stdout }}" | xargs apt-mark hold; exit 0

- include: restart_services.yml

