---

- hosts: env_{{ env_id }}
  any_errors_fatal: true

  vars_files:
    - "vars/mos_releases/{{ mos_release }}.yml"
    - "vars/steps/rollback.yml"

  tasks:
    - include: tasks/apt_update.yml

    - include: tasks/gather_customizations.yml

    - include: tasks/verify_patches.yml

    - include: tasks/rollback_upgrade.yml

    - include: tasks/apply_patches.yml

- include: restart_services.yml

