---

- hosts: all:!fuel

  vars_files:
    - "vars/mos_releases/{{ mos_release }}.yml"
    - "vars/steps/verify_patches.yml"

  tasks:
    - include: tasks/apt_update.yml

    - include: tasks/verify_customizations.yml

    - include: tasks/verify_patches.yml

