---

- hosts: all:!fuel

  vars_files:
    - "vars/mos_releases/{{ mos_release }}.yml"
    - "vars/steps/{{ steps }}.yml"

  tasks:
    - include: tasks/apt_update.yml
      when: apt_update

    - include: tasks/get_current_mu.yml

    - include: tasks/verify_md5.yml

